version: '3.7'

services:
  backend:
    image: integration-tests-backendapp
    network_mode: host
    build:
      context: .
      dockerfile: integration-tests.dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock